### ISSUE TITLE
`isequal` for `SortedDict` too strict

### ISSUE THREAD

**Issue by kmsquire** [JuliaCollections/DataStructures.jl#167]
Minor thing I noticed while fixing up #166...

Since julia doesn't have strong typing, it doesn't usually require types to be equal in order to compare them.  For example

``` julia
julia> a
Dict{Any,Any} with 2 entries:
  2 => 3
  1 => 2

julia> b
Dict{Int64,Int64} with 2 entries:
  2 => 3
  1 => 2

julia> isequal(a,b)
true
```

However, `SortedDict` is a bit stricter, and this should probably be loosened to match the behavior in base.

``` julia
julia> x
DataStructures.SortedDict{Any,Any,Base.Order.ForwardOrdering} with 2 entries:
  1 => 2
  2 => 3

julia> y
DataStructures.SortedDict{Int64,Int64,Base.Order.ForwardOrdering} with 2 entries:
  1 => 2
  2 => 3

julia> isequal(x,y)
ERROR: Cannot use isequal for two SortedDicts unless their element types and ordering objects are equal
 in isequal at /Users/kevin/.julia/v0.4/DataStructures/src/sortedDict.jl:228
```

To be fair, the equality waters are somewhat murky (to me), especially when it comes to container equality.

Cc: @StephenVavasis

**Comment by kmsquire** [comment]
In fact, I we can even compare dictionaries of different types:

```julia
julia> a
Dict{Any,Any} with 2 entries:
  2 => 3
  1 => 2

julia> b
DataStructures.SortedDict{Int64,Int64,Base.Order.ForwardOrdering} with 2 entries:
  1 => 2
  2 => 3
```

**Comment by kmsquire** [comment]
```julia
julia> isequal(a,b)
true
```

**Comment by athulappadan** [comment]
SortedDict is comparing the _`eltype`_ of both dictionaries which results in getting the error message.

`if !isequal(ord, orderobject(m2)) || !isequal(eltype(m1), eltype(m2))`

**Comment by athulappadan** [comment]
I defined a new function which returns the type of the first element of a SortedDict and used it instead of eltype.

**Comment by StephenVavasis** [comment]
This topic is rather complicated because you could have two SortedDicts with exactly the same key/value  entries but with different key orderings.  Perhaps the best solution is to replace the current 'isequal' routine with the simpler:

isequal(s::SortedDict, t::SortedDict) = isequal(collect(s), collect(t))

This would mean that two sorted dicts are equal if, when their key/value pairs are pulled out in sorted order, two arrays are obtained that have entrywise equal elements?  The above statement has clear syntax and interpretation.  Its disadvantage is that it requires the creation of two potentially large temporary arrays.  However, anyone using 'isequal' on SortedDict's is probably not so concerned about performance anyway.

**Comment by laborg** [comment]
This isn't a problem anymore:
```julia-repl
julia> a=SortedDict{Any,Any}(2=>3,1=>2)
SortedDict{Any, Any, Base.Order.ForwardOrdering} with 2 entries:
  1 => 2
  2 => 3

julia> b=SortedDict{Int,Int}(2=>3,1=>2)
SortedDict{Int64, Int64, Base.Order.ForwardOrdering} with 2 entries:
  1 => 2
  2 => 3

julia> isequal(a,b)
true
```
