### ISSUE TITLE
Sorted Containers: interplay of iteration and mutation

### ISSUE THREAD

**Issue by ettersi** [JuliaCollections/DataStructures.jl#282]
Consider the following:
```
julia> sc = SortedSet([1])
       for v in sc
           push!(sc,3)
           println(v)
       end
1

julia> sc = SortedSet([1,2])
       for v in sc
           push!(sc,3)
           println(v)
       end
1
2
3

julia> sc = SortedSet([1])
       st = startof(sc)
       while status((sc,st)) != 3
           push!(sc,3)
           println(deref((sc,st)))
           st = advance((sc,st))
       end
1
3
```
I think the "standard" iteration should behave just like the last example. Is there a reason why it doesn't?

**Comment by StephenVavasis** [comment]
If you look up the following chapter of the documentation:

https://docs.julialang.org/en/stable/stdlib/collections/

you will see that in a for-loop, the iteration counter is incremented at the beginning of the loop-body rather than the end.  This is useful for several reasons.  For example, this feature makes it possible to write a loop in which the "current" item of a  container is deleted.

Iterating over a container while simultaneously inserting items into it is a tricky business and may lead to unexpected results.

**Comment by ettersi** [comment]
Ok, I see why it's not really possible to provide what I want using the for-loop syntax. I think it's a bit arbitrary to support deletion and not insertion, but I guess that ship sailed once Julia decided to merge dereferencing and advancing into a single function. And I'm starting to realise that this is one more instance of a problem which seems simple but turns out to be incredibly complicated.

**Comment by oxinabox** [comment]
seems like there is nothing actionable on the behalf of the package.
But might be an interesting discussion on Slack or Discourse.
