### ISSUE TITLE
Migrate doc from Sphinx to Documenter

### ISSUE THREAD

**Issue by scls19fr** [JuliaCollections/DataStructures.jl#346]
https://github.com/JuliaCollections/DataStructures.jl/issues/345#issuecomment-343831010

What are the pros and cons?

**Comment by kmsquire** [comment]
Cons: needs someone to do the work.

Pros: Allows doctests.  Keeps everything inside of the Julia ecosystem.

Other than doctests, it's a bit less work to simply keep things the way they are, but I'm fully supportive if someone has the time to make this change.  I started to at one point, but dropped it because of lack of time.

**Comment by kmsquire** [comment]
See also https://github.com/JuliaStats/TimeSeries.jl/pull/342#issuecomment-343829156

**Comment by scls19fr** [comment]
Pros: Markdown syntax easier than reStructuredText
Cons: reStructuredText probably richer then Markdown.
