### ISSUE TITLE
UnitRange{DataStructures.Tokens.IntSemiToken}

### ISSUE THREAD

**Issue by denius** [JuliaCollections/DataStructures.jl#778]
Dear all,

I'm very need to store an `UnitRange`s of `IntSemiToken` in my development package (then I can iterate over this diapason later). Just to store. This is because `searchsorted` has the `UnitRange` interface and my package makes extensive use of this feature. Of course, I can create them privately, but that would be type piracy, which is not right.

Is it possible to have the definition of `UnitRange{IntSemiToken}` in `DataStructures`?

MWE:
```julia
julia> D = SortedDict(1=>2.0, 2=>3.0)
SortedDict{Int64, Float64, Base.Order.ForwardOrdering} with 2 entries:
  1 => 2.0
  2 => 3.0

julia> st = startof(D)
DataStructures.Tokens.IntSemiToken(3)

julia> st:st
ERROR: MethodError: no method matching -(::DataStructures.Tokens.IntSemiToken, ::DataStructures.Tokens.IntSemiToken)
Stacktrace:
 [1] (::Colon)(start::DataStructures.Tokens.IntSemiToken, stop::DataStructures.Tokens.IntSemiToken)
   @ Base ./range.jl:7
 [2] top-level scope
   @ REPL[21]:1
```

P.S. The package will be the `UnitRangesSortedSets`, almost done.

**Comment by StephenVavasis** [comment]
When the sorted containers were originally written, there was significant overhead associated with manipulating tokens, which is why semitokens were added to the API.  As a reminder, a token is a length-two tuple consisting of a reference to the entire container and an index of a particular entry.  Semitokens are the second half of the token.  As of Julia 1.5.1, apparently the overhead for tokens is greatly diminished, so it may be sensible to expand their usage.

The reason I mention this is that it would make more sense to have UnitRange of tokens rather than semitokens.  This is because if a and b are semitokens, then a:b incompletely specifies a range.  On the other hand, if a and b are tokens, then a:b is self-contained.  So the latter seems preferable to me.

**Comment by denius** [comment]
Of course you are right, I didn't realize that I had `length` and `iterator` (in addition to `delete!` and `getindex`) and they would not work in isolation from the data.

After a little thought, I came up with my ranges:
```julia
struct IntSemiTokenRange{T<:DataStructures.Tokens.IntSemiToken,K,D} <: AbstractUnitRange{T}
    start::T
    stop::T
    data::SortedDict{K,D}
end
```

Thank you very much for your attention to my question.
